Repository wanted-quantum-jump/FeedMoa, pull requests merged in 2023-10, with the labels that each got.

#5 feat: 게시글 엔티티 및 기본 코드 작성
  build.gradle
  src/main/java/com/skeleton/common/config/JpaConfig.java
  src/main/java/com/skeleton/common/entity/BaseTimeEntity.java
  src/main/java/com/skeleton/feed/controller/PostController.java
  src/main/java/com/skeleton/feed/entity/Post.java
  src/main/java/com/skeleton/feed/enums/SnsType.java
  src/main/java/com/skeleton/feed/repository/PostRepository.java
  src/main/java/com/skeleton/feed/service/PostService.java
Labels: enhancement

#6 chore: 데이터베이스 관련 설정 초기화
  build.gradle
  src/main/resources/application.properties
Labels: enhancement

#8 feat: 해시태그 모델링
  src/main/java/com/skeleton/feed/entity/Hashtag.java
  src/main/java/com/skeleton/feed/entity/Post.java
  src/main/java/com/skeleton/feed/entity/PostHashtag.java
  src/main/java/com/skeleton/feed/repository/HashtagRepository.java
  src/main/java/com/skeleton/feed/repository/PostHashtagRepository.java
Labels: enhancement

#14 feat: 공통 에러 처리 코드 작성
  src/main/java/com/skeleton/common/exception/CustomException.java
  src/main/java/com/skeleton/common/exception/ErrorCode.java
  src/main/java/com/skeleton/common/exception/ErrorResponse.java
  src/main/java/com/skeleton/common/exception/GlobalExceptionHandler.java
Labels: enhancement

#20 chore: 스프링 시큐리티, jwt 의존성 추가 및 초기 설정
  build.gradle
  src/main/java/com/skeleton/auth/config/SecurityConfig.java
Labels: enhancement

#24 fix: 스프링 시큐리티 설정의 접근 허용 코드 수정
  src/main/java/com/skeleton/auth/config/SecurityConfig.java
Labels: bug

#21 feat: 게시물 좋아요 API 구현
  src/main/java/com/skeleton/common/config/RestTemplateConfig.java
  src/main/java/com/skeleton/common/exception/ErrorCode.java
  src/main/java/com/skeleton/feed/controller/PostController.java
  src/main/java/com/skeleton/feed/dto/AddLikeResponse.java
  src/main/java/com/skeleton/feed/entity/Post.java
  src/main/java/com/skeleton/feed/service/PostService.java
  src/main/java/com/skeleton/feed/service/SnsApiCallerService.java
  src/test/java/com/skeleton/feed/PostDummyMaker.java
Labels: enhancement

#25 feat: 회원가입 API 구현
  src/main/java/com/skeleton/common/exception/ErrorCode.java
  src/main/java/com/skeleton/user/controller/UserController.java
  src/main/java/com/skeleton/user/crypto/PasswordEncoder.java
  src/main/java/com/skeleton/user/dto/UserSignupRequest.java
  src/main/java/com/skeleton/user/dto/UserSignupResponse.java
  src/main/java/com/skeleton/user/entity/User.java
  src/main/java/com/skeleton/user/repository/UserRepository.java
  src/main/java/com/skeleton/user/service/UserService.java
Labels: enhancement

#30 Feature/10 jwt authentication authorization
  src/main/java/com/skeleton/auth/config/JwtAuthenticationProvider.java
  src/main/java/com/skeleton/auth/config/SecurityConfig.java
  src/main/java/com/skeleton/auth/controller/AuthController.java
  src/main/java/com/skeleton/auth/enums/TokenType.java
  src/main/java/com/skeleton/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/skeleton/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/skeleton/auth/jwt/JwtUtils.java
  src/main/java/com/skeleton/common/exception/ErrorCode.java
Labels: enhancement

#34 feat: verify api 추가로 인한 security config 수정
  src/main/java/com/skeleton/auth/config/SecurityConfig.java
Labels: enhancement

#32 feat: 가입승인 API 구현
  src/main/java/com/skeleton/common/exception/ErrorCode.java
  src/main/java/com/skeleton/user/controller/UserController.java
  src/main/java/com/skeleton/user/dto/UserVerifyRequest.java
  src/main/java/com/skeleton/user/entity/User.java
  src/main/java/com/skeleton/user/enums/UserVerification.java
  src/main/java/com/skeleton/user/service/UserService.java
Labels: enhancement

#35 docs: README에 API 문서 추가
  README.md
Labels: documentation
